"""Utilities for reporting matched model feature-ablation experiments."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict


def _arm_summary(result: Dict[str, Any], feature_set: str) -> Dict[str, Any]:
    test_metrics = result.get("test_metrics", {})
    test_auroc = test_metrics.get("test_auroc")
    if test_auroc is None:
        raise ValueError(f"{feature_set} result is missing held-out test AUROC")

    summary = {
        "feature_set": feature_set,
        "best_model": result.get("best_model"),
        "n_features": len(result.get("feature_cols", [])),
        "held_out_test_auroc": float(test_auroc),
    }
    for metric in ("auprc", "brier", "recall", "specificity"):
        value = test_metrics.get(f"test_{metric}")
        summary[f"held_out_test_{metric}"] = float(value) if value is not None else None
    return summary


def build_comparison_report(
    full_result: Dict[str, Any],
    no_labs_result: Dict[str, Any],
    provenance: Dict[str, Any],
) -> Dict[str, Any]:
    """Build an auditable full-vs-no-labs held-out performance report."""
    full = _arm_summary(full_result, "full")
    no_labs = _arm_summary(no_labs_result, "no_labs")
    delta = no_labs["held_out_test_auroc"] - full["held_out_test_auroc"]

    return {
        "experiment": "matched_no_labs_ablation",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "claim_scope": "synthetic development evidence only",
        "data_provenance": provenance,
        "comparison": {
            "full": full,
            "no_labs": no_labs,
        },
        "auroc_delta_no_labs_minus_full": float(delta),
        "method": (
            "Both arms use identical patient-level train, validation, and held-out test "
            "splits. The no-labs arm excludes lactate, WBC, procalcitonin, all derived "
            "lab trajectories, and every lab-missingness indicator before retraining."
        ),
        "limitations": [
            "The cohort is generated by a hand-authored synthetic data process.",
            "The result is not clinical validation and cannot establish performance in patients.",
            "External retrospective and prospective validation remain required.",
        ],
    }


def add_uncertainty(
    report: Dict[str, Any],
    full_result: Dict[str, Any],
    no_labs_result: Dict[str, Any],
    n_boot: int = 1000,
    seed: int = 0,
    level: float = 0.95,
) -> Dict[str, Any]:
    """Attach paired patient-level bootstrap CIs to a comparison report.

    Both arms must have been scored on the same held-out rows (same patients,
    order and labels); otherwise the comparison is not paired and this raises.
    The bootstrap's point estimates must reproduce the reported held-out
    metrics, which guards against attaching intervals for different data.
    """
    from sepsis_vitals.ml.uncertainty import paired_cluster_bootstrap

    full, no_labs = full_result.get("test_predictions"), no_labs_result.get("test_predictions")
    if not full or not no_labs:
        raise ValueError("both results need test_predictions (run_pipeline returns them)")
    if full["patient_id"] != no_labs["patient_id"] or full["y_true"] != no_labs["y_true"]:
        raise ValueError("the arms were not evaluated on the same held-out rows")

    uncertainty = paired_cluster_bootstrap(
        full["patient_id"], full["y_true"],
        {"full": full["y_prob"], "no_labs": no_labs["y_prob"]},
        reference="full", n_boot=n_boot, seed=seed, level=level,
    )
    for arm in ("full", "no_labs"):
        reported = report["comparison"][arm]["held_out_test_auroc"]
        recomputed = uncertainty["arms"][arm]["auroc"]["estimate"]
        if abs(reported - recomputed) > 5e-4:
            raise ValueError(f"{arm}: bootstrap AUROC {recomputed} does not match reported {reported:.4f}")
    report["uncertainty"] = uncertainty
    report["limitations"] = list(report["limitations"]) + [
        "Confidence intervals cover sampling variability of the synthetic held-out set given "
        "the trained models; they exclude training variability and say nothing about patients.",
    ]
    return report
