"""Utilities for reporting matched model feature-ablation experiments."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict


def _arm_summary(result: Dict[str, Any], feature_set: str) -> Dict[str, Any]:
    test_metrics = result.get("test_metrics", {})
    test_auroc = test_metrics.get("test_auroc")
    if test_auroc is None:
        raise ValueError(f"{feature_set} result is missing held-out test AUROC")

    summary = {
        "feature_set": feature_set,
        "best_model": result.get("best_model"),
        "n_features": len(result.get("feature_cols", [])),
        "held_out_test_auroc": float(test_auroc),
    }
    for metric in ("auprc", "brier", "recall", "specificity"):
        value = test_metrics.get(f"test_{metric}")
        summary[f"held_out_test_{metric}"] = float(value) if value is not None else None
    return summary


def build_comparison_report(
    full_result: Dict[str, Any],
    no_labs_result: Dict[str, Any],
    provenance: Dict[str, Any],
) -> Dict[str, Any]:
    """Build an auditable full-vs-no-labs held-out performance report."""
    full = _arm_summary(full_result, "full")
    no_labs = _arm_summary(no_labs_result, "no_labs")
    delta = no_labs["held_out_test_auroc"] - full["held_out_test_auroc"]

    return {
        "experiment": "matched_no_labs_ablation",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "claim_scope": "synthetic development evidence only",
        "data_provenance": provenance,
        "comparison": {
            "full": full,
            "no_labs": no_labs,
        },
        "auroc_delta_no_labs_minus_full": float(delta),
        "method": (
            "Both arms use identical patient-level train, validation, and held-out test "
            "splits. The no-labs arm excludes lactate, WBC, procalcitonin, all derived "
            "lab trajectories, and every lab-missingness indicator before retraining."
        ),
        "limitations": [
            "The cohort is generated by a hand-authored synthetic data process.",
            "The result is not clinical validation and cannot establish performance in patients.",
            "External retrospective and prospective validation remain required.",
        ],
    }
